### ISSUE TITLE
矩形框type返回json错误。

### ISSUE THREAD

**Issue by 365436741** [zhuguibiao/canvas-mark-board#2]
在线demo画矩形框的时候的到的json数据type不是rect。返回了错误的polygon。
[{"id":"abcd408a-5836-40f7-9628-f77eb497cc65","label":"person","type":"polygon","color":"#ff0000","select":false,"pointList":[{"x":145.67969587679113,"y":88.83516911979724},{"x":318.3592942781948,"y":167.68885856321276}]}]

**Comment by zhuguibiao** [comment]
这是一个bug，rect 类型写错了，后续更新
